// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class Banner
    {
        public int BannerId { get; set; }
        public string Imagen { get; set; }
        public bool FlagActivo { get; set; }
    }
}