// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class Categoria
    {
        public Categoria()
        {
            Evento = new HashSet<Evento>();
        }

        public int CategoriaId { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<Evento> Evento { get; set; }
    }
}