// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class EventoFecha
    {
        public EventoFecha()
        {
            OrdenDetalle = new HashSet<OrdenDetalle>();
        }

        public int EventoFechaId { get; set; }
        public int? EventoId { get; set; }
        public DateTime? Fecha { get; set; }
        public bool? FlagEliminado { get; set; }

        public virtual Evento Evento { get; set; }
        public virtual ICollection<OrdenDetalle> OrdenDetalle { get; set; }
    }
}