// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class Evento
    {
        public Evento()
        {
            EventoEntrada = new HashSet<EventoEntrada>();
            EventoFecha = new HashSet<EventoFecha>();
            OrdenDetalle = new HashSet<OrdenDetalle>();
        }

        public int EventoId { get; set; }
        public string Nombre { get; set; }
        public string Informacion { get; set; }
        public string Ubicacion { get; set; }
        public int? CategoriaId { get; set; }
        public decimal CapacidadTotal { get; set; }
        public bool? FlagEliminado { get; set; }
        public string Imagen { get; set; }

        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<EventoEntrada> EventoEntrada { get; set; }
        public virtual ICollection<EventoFecha> EventoFecha { get; set; }
        public virtual ICollection<OrdenDetalle> OrdenDetalle { get; set; }
    }
}