// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class EventoEntrada
    {
        public EventoEntrada()
        {
            OrdenDetalle = new HashSet<OrdenDetalle>();
        }

        public int? EventoId { get; set; }
        public int EventoEntradaId { get; set; }
        public string Tipo { get; set; }
        public decimal? PrecioRegular { get; set; }
        public decimal? PrecioDescuento { get; set; }
        public DateTime? FechaVigenciaDescuento { get; set; }
        public int? Capacidad { get; set; }
        public bool? FlagEliminado { get; set; }

        public virtual Evento Evento { get; set; }
        public virtual ICollection<OrdenDetalle> OrdenDetalle { get; set; }
    }
}