// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class Orden
    {
        public Orden()
        {
            OrdenDetalle = new HashSet<OrdenDetalle>();
        }

        public int OrdenId { get; set; }
        public int? UsuarioId { get; set; }
        public DateTime? FechaOrden { get; set; }
        public decimal? PrecioTotal { get; set; }
        public string Estado { get; set; }
        public string MedioPago { get; set; }
        public string NumeroOperacion { get; set; }
        public bool TicketGenerado { get; set; }

        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<OrdenDetalle> OrdenDetalle { get; set; }
    }
}