// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class OrdenTicket
    {
        public int OrdenTicketId { get; set; }
        public int OrdenId { get; set; }
        public int EventoId { get; set; }
        public int EventoEntradaId { get; set; }
        public int EventoFechaId { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public bool FlagNominado { get; set; }
    }
}