// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            Orden = new HashSet<Orden>();
        }

        public int UsuarioId { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombreUsuario { get; set; }
        public string Email { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public string Rol { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public virtual ICollection<Orden> Orden { get; set; }

    }
}