// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Entradas.Shared.Models
{
    public partial class VwOrdenTicket
    {
        public int OrdenTicketId { get; set; }
        public int OrdenId { get; set; }
        public string Evento { get; set; }
        public string Tipo { get; set; }
        public DateTime? Fecha { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public bool FlagNominado { get; set; }
    }
}