// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entradas.Shared.Models
{
    public partial class VwOrden
    {
        public int OrdenId { get; set; }
        public int? UsuarioId { get; set; }
        public string Evento { get; set; }
        public DateTime? Fecha { get; set; }
        public int? Cantidad { get; set; }
        public decimal? PrecioUnitario { get; set; }
        public decimal? PrecioTotal { get; set; }
        public string TipoEntrada { get; set; }
    }
}